language: node_js
node_js:
    - '14'
script:
    - npm install
    - npm run lint
    - npm run compile
    - node lib/auto.js
notifications:
    webhooks:
        urls:
            - 'https://www.travisbuddy.com/'
        on_success: never
        on_failure: always
        on_start: never
        on_cancel: never
        on_error: never
